# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

- name: 'Sync your forks'
  uses: 'sudo-bot/action-fork-sync@v1.0.4'
  with:
 source-url: "https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/tailwindlabs/heroicons.git"
        # Give repo scope to token and access to myname/officialproject-fork for a token user != myname (eg: a bot)
        fork-url: "https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/infernox64/heroicons.git"
        
        clone-depth: "100" # optional, defaults to 100
        
        - name: Setup Node.js environment
  uses: actions/setup-node@v1.4.3
  with:
    # Set always-auth in npmrc
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
    node-version: 12.x# optional, default is 10.x


    # Deprecated. Use node-version instead. Will not be supported after October 1, 2019
    #version: # optional
    - name: Update Node Dependencies
  uses: neverendingqs/gh-action-node-update-deps@v1.2.1
  with:
    # If set, bumps the package version based on value (e.g. patch)
    bump-version: "patch"  # optional, default is 
    # Git user.email to use for the commit.
    git-user-email: "infernox64@gmail.com"
    # Git user.name to use for the commit.
    git-user-name:"infernox64"
    # Set to 'yarn' to use yarn. Defaults to npm.
    package-manager: "npm" # optional, default is npm
    
    uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: path/to/artifact/world.txt
    
    
    
